const projects=[
{title:'視障者捷運輔助系統',short:'讓移動，<br>更自主。',en:'ACCESSIBLE MOBILITY',cat:'design',label:'互動設計',type:'課程團隊專案',color:'#263850',image:'hci-screen.png',cls:'hci',pdf:1,video:'prototype',desc:'以視障者的捷運通勤情境，探索低負擔的導航體驗。',sections:[['專案背景','聚焦重度視障者在轉乘與出口導引時的資訊需求，以先嗇宮—古亭—公館的通勤路線為設計情境。'],['研究與設計','團隊透過文獻回顧、次級資料分析、親和圖與 Persona 整理需求，再設計結合室內導航、語音、震動及緊急求助的 App 原型。'],['評估與反思','以 Nielsen 十項可用性原則進行準則性評估，依組內與班級回饋修正。作品屬概念原型，實際使用者驗證與技術實作仍是後續研究方向。']]},
{title:'New Wave 企業知識稽核',short:'讓知識，<br>持續流動。',en:'KNOWLEDGE AUDIT',cat:'knowledge',label:'知識管理',type:'課程團隊專案',color:'#39524c',image:'cover-4.png',pdf:4,desc:'從組織訪談出發，梳理知識保存、分享與移轉。',sections:[['專案背景','以 New Wave Lending Group 臺灣分公司為對象，分析組織任務、資訊環境與知識管理現況。'],['分析方法','透過訪談與知識稽核，檢視知識儲存、Hot Spots、KSEI 與知識螺旋，整理工作經驗如何在組織內流動。'],['成果與建議','提出文件命名與版本管理、Handbook 完善，以及跨國交流等改善方向，協助隱性經驗轉化為可保存的組織知識。']]},
{title:'ChatGPT × 語言學習行為',short:'當 AI 成為<br>學習夥伴。',en:'AI & INFORMATION BEHAVIOR',cat:'research',label:'資訊行為研究',type:'研究計畫',color:'#513f69',image:'cover-5.png',pdf:5,desc:'探討大學生使用 ChatGPT 學習英語時的資訊行為。',sections:[['研究問題','關注臺灣大學生的學習動機、資訊需求、互動策略，以及對 ChatGPT 回應的評估與驗證。'],['規劃方法','計畫結合問卷、半結構式訪談及自願提供的對話紀錄，使用量化分析與主題分析互相對照。'],['作品階段','此附件為研究計畫申請書，呈現研究設計、預期成果與時程規劃，並非已完成的實證研究結果。']]},
{title:'教養風格與學業成就',short:'從數據，<br>理解關係。',en:'QUANTITATIVE RESEARCH',cat:'research',label:'心理統計',type:'課程團隊專案',color:'#584632',image:'cover-2.png',pdf:2,desc:'運用 TEPS 資料，分析情感支持、規範與學業表現。',sections:[['研究背景','以台灣教育長期追蹤資料庫 TEPS 第二波（2003）國中生資料，探討主要照顧者教養風格與學業成就的關係。'],['分析方法','報告使用 7,280 筆分析樣本，從情感回應與規範要求兩個維度整理資料，並比較不同群體的迴歸結果。'],['成果','完成研究問題設定、資料描述、分組分析與結果討論。以觀察資料呈現變項間的關聯，解讀時需考量資料與研究設計限制。']]},
{title:'陳澄波研究資料集',short:'為研究，<br>整理線索。',en:'BIBLIOGRAPHY & CURATION',cat:'knowledge',label:'目錄學',type:'課程團隊專案',color:'#614445',image:'cover-3.png',pdf:3,desc:'以專題目錄串聯藝術家生平、創作與歷史資料。',sections:[['編纂主題','圍繞陳澄波建立研究資料集，整理綜合性著作、傳記、藝術風格、歷史處境及延伸研究。'],['資訊組織','訂定收錄範圍、分類原則與著錄方式，納入展覽圖錄、兒童與青少年導讀、數位多媒體及個人史料。'],['作品成果','以結構化目錄提供主題探索入口，讓不同型態的資料能在同一研究脈絡下被找到與理解。']]},
{title:'兒童讀物影音作品',short:'讓故事，<br>走進畫面。',en:'READING & STORYTELLING',cat:'film',label:'影音創作',type:'課程影音作品',color:'#333b41',image:'reading.jpg',cls:'film',video:'reading',desc:'透過影音呈現兒童讀物相關課程作品。',sections:[['作品形式','兒童讀物課程影音作品，可直接播放完整影片。']]}
];
const grid=document.querySelector('#grid');
grid.innerHTML=projects.map((p,i)=>`<article class="card" data-category="${p.cat}"><button class="card-button" data-project="${i}" aria-label="閱讀${p.title}"><div class="poster ${p.cls||''}" style="--poster:${p.color}"><span class="number">PROJECT / 0${i+1}</span><h3>${p.short}</h3><span class="english">${p.en}</span><img src="assets/${p.image}" alt="" loading="lazy">${p.video?'<span class="play" aria-hidden="true">▷</span>':''}</div><div class="card-meta"><span>${p.label}</span><span>${p.type}</span></div><h3 class="card-title">${p.title} ↗</h3><p class="card-description">${p.desc}</p></button></article>`).join('');
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b?'true':'false')});let n=0;document.querySelectorAll('.card').forEach(c=>{c.hidden=b.dataset.filter!=='all'&&c.dataset.category!==b.dataset.filter;if(!c.hidden)n++});document.querySelector('#count').textContent=`顯示 ${n} 件作品`;}));
const detail=document.querySelector('#detail'),player=document.querySelector('#player'),video=player.querySelector('video');
document.addEventListener('click',e=>{const project=e.target.closest('[data-project]');if(project){const p=projects[Number(project.dataset.project)];document.querySelector('#detail-body').innerHTML=`<p class="eyebrow">${p.en} / ${p.type}</p><h2 id="detail-title">${p.title}</h2><p>${p.desc}</p>${p.sections.map(([h,t])=>`<h3>${h}</h3><p>${t}</p>`).join('')}<div class="actions">${p.pdf!==undefined?`<a class="primary" href="assets/project-${p.pdf}.pdf" target="_blank" rel="noopener">閱讀完整 PDF ↗</a>`:''}${p.video?`<button class="secondary" data-video="${p.video}">▷ 播放影片</button>`:''}</div>`;detail.showModal();}const play=e.target.closest('[data-video]');if(play){document.querySelector('#video-title').textContent=play.dataset.video==='prototype'?'視障者捷運輔助系統 — 原型影片':'兒童讀物影音作品';video.src=`assets/${play.dataset.video}.mp4`;video.poster=`assets/${play.dataset.video}.jpg`;player.showModal();}if(e.target.closest('.close'))e.target.closest('dialog').close();});
player.addEventListener('close',()=>{video.pause();video.removeAttribute('src');video.load()});
for(const d of [detail,player])d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
